concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository
    != 'apereo/cas' }}
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{
    github.event.pull_request.id }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERM: xterm-256color
jobs:
  rerun-failed-jobs:
    continue-on-error: true
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.status
      == 'completed' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Rerunning ${{ github.event.workflow_run.name }}
      run: "echo \"Workflow run ID: ${{ github.event.workflow_run.id }}\"\necho \"\
        Workflow run Name: ${{ github.event.workflow_run.name }}\"\necho \"Workflow\
        \ run attempt #: ${{ github.event.workflow_run.run_attempt }}\"\nCURRENT_ATTEMPTS=${{\
        \ github.event.workflow_run.run_attempt }}\nif [ \"$CURRENT_ATTEMPTS\" -le\
        \ 2 ]; then\n  echo \"Rerunning failed workflow jobs for workflow ${{ github.event.workflow_run.name\
        \ }}...\"\n  gh api --method POST -H \"Accept: application/vnd.github+json\"\
        \ /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id\
        \ }}/rerun-failed-jobs\nelse\n  echo \"Max run attempts reached. Not rerunning.\"\
        \nfi\n"
name: Rerun Workflow Runs
on:
  repository_dispatch:
    types: trigger-ga___reruns.yml
